<?php
require_once __DIR__ . '/../../app/core/AuthMiddleware.php';
require_once __DIR__ . '/../../app/models/Asset.php';
require_once __DIR__ . '/../../app/models/BorrowRequest.php';

$user = AuthMiddleware::authenticate();

// Ensure only admins can access
if ($user['role'] !== 'org_admin' && $user['role'] !== 'super_admin') {
    http_response_code(403);
    exit('Unauthorized');
}

$type = isset($_GET['type']) ? $_GET['type'] : 'inventory';
$startDate = isset($_GET['start_date']) ? $_GET['start_date'] : null;
$endDate = isset($_GET['end_date']) ? $_GET['end_date'] : null;

$assetModel = new Asset();
$borrowModel = new BorrowRequest();
$data = [];

if ($type === 'inventory') {
    $stmt = $assetModel->readAll($user['org_id']); // Assuming this grabs all
    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
    foreach ($rows as $row) {
        if ($startDate && substr($row['created_at'], 0, 10) < $startDate)
            continue;
        if ($endDate && substr($row['created_at'], 0, 10) > $endDate)
            continue;
        $data[] = $row;
    }
    $title = "Asset Inventory Report";
} else {
    $stmt = $borrowModel->getAll($user['org_id']); // Assuming this grabs all
    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
    foreach ($rows as $row) {
        if ($startDate && substr($row['created_at'], 0, 10) < $startDate)
            continue;
        if ($endDate && substr($row['created_at'], 0, 10) > $endDate)
            continue;
        $data[] = $row;
    }
    $title = "Borrowing Activity Report";
}

?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>
        <?php echo $title; ?> - Print View
    </title>
    <style>
        body {
            font-family: sans-serif;
            padding: 20px;
            font-size: 12px;
        }

        h1 {
            margin-bottom: 5px;
        }

        .meta {
            color: #666;
            margin-bottom: 20px;
            font-size: 10px;
        }

        table {
            w-full;
            border-collapse: collapse;
            width: 100%;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background: #f5f5f5;
            font-weight: bold;
        }

        @media print {
            body {
                padding: 0;
            }

            button {
                display: none;
            }
        }

        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
        }

        .print-btn {
            padding: 10px 20px;
            background: #006e7a;
            color: white;
            border: none;
            cursor: pointer;
            border-radius: 4px;
        }
    </style>
</head>

<body onload="window.print()">

    <div class="header">
        <div>
            <h1>
                <?php echo $title; ?>
            </h1>
            <div class="meta">
                Generated by:
                <?php echo htmlspecialchars($user['name']); ?><br>
                Date:
                <?php echo date('Y-m-d H:i'); ?><br>
                <?php if ($startDate || $endDate): ?>
                    Range:
                    <?php echo $startDate ? $startDate : 'Beginning'; ?> to
                    <?php echo $endDate ? $endDate : 'Present'; ?>
                <?php endif; ?>
            </div>
        </div>
        <button class="print-btn" onclick="window.print()">Print Report</button>
    </div>

    <table>
        <thead>
            <tr>
                <?php if ($type === 'inventory'): ?>
                    <th>Code</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Location</th>
                    <th>Status</th>
                    <th>Added</th>
                <?php else: ?>
                    <th>Requested At</th>
                    <th>Borrower</th>
                    <th>Asset</th>
                    <th>Status</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                <?php endif; ?>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($data as $item): ?>
                <tr>
                    <?php if ($type === 'inventory'): ?>
                        <td>
                            <?php echo htmlspecialchars($item['code']); ?>
                        </td>
                        <td>
                            <?php echo htmlspecialchars($item['name']); ?>
                        </td>
                        <td>
                            <?php echo htmlspecialchars($item['category']); ?>
                        </td>
                        <td>
                            <?php echo htmlspecialchars($item['location']); ?>
                        </td>
                        <td>
                            <?php echo htmlspecialchars($item['status']); ?>
                        </td>
                        <td>
                            <?php echo htmlspecialchars(substr($item['created_at'], 0, 10)); ?>
                        </td>
                    <?php else: ?>
                        <td>
                            <?php echo htmlspecialchars(substr($item['created_at'], 0, 10)); ?>
                        </td>
                        <td>
                            <?php echo htmlspecialchars($item['user_name']); ?>
                        </td>
                        <td>
                            <?php echo htmlspecialchars($item['asset_name']); ?>
                        </td>
                        <td>
                            <?php echo htmlspecialchars($item['status']); ?>
                        </td>
                        <td>
                            <?php echo htmlspecialchars($item['start_date']); ?>
                        </td>
                        <td>
                            <?php echo htmlspecialchars($item['end_date']); ?>
                        </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
            <?php if (empty($data)): ?>
                <tr>
                    <td colspan="6" style="text-align: center; color: #999;">No records found for this period.</td>
                </tr>
            <?php endif; ?>
        </tbody>
    </table>

</body>

</html>